# The URL the site will be built for
base_url = "https://trifectatech.org"

generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
title = "Trifecta Tech Foundation"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    {name = "tags", render = true},
    # {name = "ntpd-rs"},
    # {name = "announcement"},
    # {name = "zlib-rs"},
    # {name = "sudo-rs"},
    # {name = "pendulum"},
    # {name = "statime"},
    # {name = "data-compression"},
    {name = "category", render = false},
    # {name = "infrastructure"},
    # {name = "ecosystem"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
